circleci/enterprise-setup

- circleci.tf
This partially patches CVE-2016-5195 (http://dirtycow.ninja/). Services
boxes should be updated manually.
> Updated terraform script to use patched version

- circleci.tf
Tiny change to support Replicated 2. We have to use a path that is accessible to the replicated docker container. (We should come up with a better mechanism in the future instead of shoehorning things into Replicated data dirs.)
> Support Replicated 2.x

- circleci.tf
The previous AMIs would not start up correctly.
> Update services AMI list with correct AMIs for the lastest CVE.

- templates/builders_user_data.tpl
- templates/nomad_user_data.tpl
- templates/services_user_data.tpl
We have had a number of issues with containers ending up `dead` in 17.06 rolling back to 17.03.2 appears to resolve this issue.
> Rollback docker to 17.03.2

- .gitignore
Added the `.terraform` dir into .gitignore, because it's annoying seeing it in `git status`
> Remove .terraform from Git

- circleci.tf
- terraform.tfvars-dev.template
- terraform.tfvars.template
This commit makes the number of 1.0 builders configurable, and sets this to 0 in the terraform template.
The default is 1, to prevent breaking existing usages of enterprise-setup. Need to confirm how some stuff works in Server deploys before I can actually merge this.
> Do not start 1.0 builders for new deploys

- templates/circleci_policy.tpl
This is required in order to use the reusable docker machine.
> [CIRCLE-7415] Add permission to start and stop instances

- circleci.tf
The current github sg has `(from|to)_protocol` instead of `(from|to)_port`
> change from_protocol to from_port on github sg

- circleci.tf
Port 7171 on services box exposes the embedded storage server.  Build-agents need to connect to it for uploading artifacts, caches, workspaces, and test results
> [CIRCLE-8143] Allow build agents to access embedded storage

- .circleci/config.yml
- README.md
- circleci.tf
- variables.tf
For the Services box, we are currently recommending an instance with at least 32GB of RAM. Therefore changing all references of `c4.2xlarge` (16GB) and `m4.xlarge` (16GB) to `m4.2xlarge` (32GB).
[Link](https://aws.amazon.com/ec2/instance-types/) to AWS instance types list.
> Upgrade the default instance type for the services box to m4.2xlarge

- variables.tf
This addresses issue #100 by including the required base AMI (Ubuntu 14.04) for ca-central-1
I've stood up an instance there using this and all jobs in reality-check are passing. 
Internal ID: CIRCLE-12739
> add ubuntu AMI for ca-central-1

- modules/nomad-cloudinit-ubuntu-v1/templates/nomad_user_data.tpl
This PR updates the nomad config file to set the name of Nomad client nodes to its corresponding AWS instance ID.
> [Do not merge][CIRCLE-11418] Set Nomad client name to instance ID

- modules/nomad-cloudinit-ubuntu-v1/templates/nomad_user_data.tpl
This PR updates the nomad config file to set the name of Nomad client nodes to its corresponding AWS instance ID.
This is a second version of the PR, as the first was accidentally merged.
> [Do not merge][CIRCLE-11418] Set Nomad client name to instance ID v2

- modules/legacy-builder-cloudinit-ubuntu-docker-v1/templates/builders_user_data.tpl
- modules/nomad-cloudinit-ubuntu-v1/templates/nomad_user_data.tpl
- templates/services_user_data.tpl
- variables.tf
- Upgrade Replicated to 2.29.0 and Docker to 17.12.1 on the services box
- Upgrade base AMI's to Ubuntu 16.04 LTS and adjust installer scripts to account for new version.
> [CIRCLE-13383] Upgrade Replicated to Latest Version for Fresh Installation

- modules/nomad-cloudinit-ubuntu-v1/templates/nomad_user_data.tpl
Adjust the cloud init script that installs Docker for CVE 2019-5736
This change uses jq to add a single entry to the installed docker config file
Doesn't assume the presence of jq
Saves the original file to /etc/docker/daemon.json.orig
Assumes:
- the path for the docker config is /etc/docker/daemon.json
- we are able to write to the above file
> CIRCLE-16271 apply patch for CVE 2019-5736

- modules/legacy-builder-cloudinit-ubuntu-docker-v1/templates/builders_user_data.tpl
- modules/nomad-cloudinit-ubuntu-v1/templates/nomad_user_data.tpl
- templates/services_user_data.tpl
There are times where builds will stop running because the builder are out of sync with the services box.  Adding NTP to everything should help resolve this problem.
The script is configured to use Amazon's NTP servers if it detects we are running on an EC2 instance and the default config for non-AWS instances.
> Add NTP Service to Services Box, Nomad Client, and Legacy Builders

- modules/nomad-cloudinit-ubuntu-v1/templates/nomad_user_data.tpl
After latest PR i am having issues on nomad nodes:
```
+ [ -f /sys/hypervisor/uuid ]
+ head -c 3 /sys/hypervisor/uuid
+ [ ec2 == ec2 ]
test.sh: 2: [: ec2: unexpected operator
+ echo USING DEFAULT NTP CONFIGURATION
USING DEFAULT NTP CONFIGURATION
```
Reason is that we are using `bash` but not `sh` syntax
> Use /bin/bash to avoid issues with ntp configuration

- README.md
- variables.tf
The services_user_data_enabled flag is used as a bool, so it's default should be a bool.
> [RE-28] Make the user_data_flag a bool

- terraform.tfvars-dev.template
- terraform.tfvars.template
on a customer call today it became clear that there's a lot of confusion over what the `circle_secret_passphrase` value actually does... lil' bit of documentation should clear up the confusion
> Iynere secret passphrase patch

- circleci.tf
These should use cidr_blocks instead of security_groups, since we're passing cidr blocks.
> Use cidr_blocks instead of security_groups

- README.md
- circleci.tf
- modules/nomad/variables.tf
- templates/circleci_policy.tpl
- terraform.tfvars-dev.template
- terraform.tfvars.template
- variables.tf
- Add GovCloud Support
- Create a new flag to toggle GovCloud support.  The flag will adjust the ARN Partitions (aws/aws-gov-cloud) within the IAM policy.
- Update VM Service AWS Instance Types
- GovCloud does not support t2 or m4 insatnce types.  Updated the default values to t3 and m5 types.
> [RE-270][RE-271] Add Support for GovCloud

- modules/nomad-cloudinit-ubuntu-v1/templates/nomad_user_data.tpl
Update Nomad and Docker to the versions used by cloud.
Also, we don't run multiple datacenters, and us-east-1 was a lie. Cloud always used default so we have hardcoded that value in schedulerer.
> [DON'T MERGE UNTIL 2.19.0][RE-236] Update Nomad and Docker versions

- templates/services_user_data.tpl
We are currently ahead of the minor version we are using in our configs.  Dialing back to latest 2.38 patch.
> Set Replicated version to match version set in Replicated config

- circleci.tf
- templates/circleci_policy.tpl
As of
https://github.com/circleci/picard-services/commit/764d5519cc820dc8583780ab12528a7a71b53933,
output-processor now needs to call iam:GetRole, so we need to modify
the policy to allow this.
> [CIRCLE-26218] Modify policy to allow calls to iam:GetRole
